version: '3.8'

services:
  bot:
    build: .
    environment:
      - APP_ENV=production
    volumes:
      - ./config:/app/config
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
